

#' making paths uniform
#' @param path path to be sanitized
#' @return sanitized path
#' @export
sanitize_path <- function(path){
  path <- stringr::str_replace(    path, "^ *", "")
  path <- ifelse( !grepl("^/", path),  paste0("/", path), path)
  return(path)
}




#' transfroming permissions into regular expressions
#' @param permissions the permissions to be transformed
#' @export
sanitize_permission_values <- function(permission_value){
  tmp <- sanitize_path(permission_value)

  tmp <- stringr::str_replace_all(tmp, "\\?", "\\\\?") # escape questionmarks
  tmp <- stringr::str_replace_all(tmp, "\\*",".*")     # translate '*' to '.*'
  tmp <- stringr::str_replace_all(tmp, "^/","^/")
  tmp <- stringr::str_replace_all(tmp, "/$","")
  tmp <- stringr::str_replace_all(tmp, "^\\^$","^/")

  return(tmp)
}




#' check if a bot has permissions to access page
#' @param permissions data.frame generated by \code{rt_get_permissions()} with
#'  three columns: 'useragent' (name of the bot), 'permission' (permission
#'  granted: Disallow/Allow) and 'value' (path for which permission applies)
#' @param bot name of the bot, defaults to "*"
#' @seealso \link{paths_allowed}
#' @param path path for which to check bot's permission, defaults to "/"
#' @export

path_allowed <- function(permissions, path="/", bot="*"){

  # checking and initializetion
  stopifnot(length(bot)==1)
  if( is.null(bot) | bot=="" | is.na(bot) ) bot <- "*"
  perm_sanitized <- within(permissions, value <- sanitize_permission_values(value))
  path <- sanitize_path(path)

  # subsetting to permissions relevant to bot
  perm_applicable <-
    perm_sanitized[
      grepl("\\*", perm_sanitized$useragent) | tolower(bot)==tolower(perm_sanitized$useragent),
      ]

  # checking which permissions are applicable to path
  perm_applicable <-
    perm_applicable[
      sapply(perm_applicable$value, grepl, x=path),
    ]

  # deciding upon rules
  # no permissions --> TRUE
  if( dim(perm_applicable)[1]==0 ){
    return(TRUE)
  }
  # only disallows --> FALSE
  if ( all(grepl("disallow", perm_applicable$permission, ignore.case = TRUE)) ){
    return(FALSE)
  }
  # only allows --> TRUE
  if ( all(grepl("^allow", perm_applicable$permission, ignore.case = TRUE)) ){
    return(TRUE)
  }
  # diverse permissions but bot specific all disallow
  if ( all(grepl("disallow", with(perm_applicable, permission[tolower(useragent)==tolower(bot)]), ignore.case = TRUE)) ){
    return(FALSE)
  }
  # diverse permissions but bot specific all allow
  if ( all(grepl("^allow", with(perm_applicable, permission[tolower(useragent)==tolower(bot)]), ignore.case = TRUE)) ){
    return(FALSE)
  }
  # diverse permissions ??? --> TRUE because no valid specification?
  if (
    any(grepl("disallow", perm_applicable$permission, ignore.case = TRUE)) &
    any(grepl("^allow", perm_applicable$permission, ignore.case = TRUE))
  ){
    return(NA)
  }
}

#' check if a bot has permissions to access page
#'
#' wrapper to \code{\link{path_allowed}}
#' @param permissions data.frame generated by \code{rt_get_permissions()} with
#'  three columns: 'useragent' (name of the bot), 'permission' (permission
#'  granted: Disallow/Allow) and 'value' (path for which permission applies)
#' @param bot name of the bot, defaults to "*"
#' @param path path for which to check bot's permission, defaults to "/"
#' @seealso \link{path_allowed}
#' @export
paths_allowed <- function(permissions, paths="/", bot="*"){
  sapply(paths, path_allowed, permissions=permissions, bot=bot)
}

